### ISSUE TITLE
Umlet throws errors

### ISSUE THREAD

**Issue by gladykov** [yuzutech/umlet#3] opened 2024-02-26 15:13 UTC
We are using yuzutech/kroki:0.24.1

We use such input
[diagram_umlet_in.txt](https://github.com/yuzutech/kroki/files/14406485/diagram_umlet_in.txt)

and get such result:
![image-20240226-142036](https://github.com/yuzutech/kroki/assets/24669884/6ae41b1f-bc16-47a8-a165-b64f6d149d03)

-------------

Issue does not exists when using standalone:
https://www.umlet.com/download/umlet_15_1/umlet-standalone-15.1.zip

![image](https://github.com/yuzutech/kroki/assets/24669884/71b5ba9a-cdac-4436-aca0-242768c05fe1)

**Comment by ggrossetie** [comment] 2024-03-02 14:58
We are compiling UMlet to a native binary using GraalVM: https://github.com/yuzutech/umlet 
We most likely need to provide this example while building the native image (otherwise some dynamic parts will be missing)

**Comment by ggrossetie** [comment] 2024-03-31 14:09
I can still reproduce this issue with the latest release 😞 

https://kroki.io/umlet/svg/eNrlmkFvmzAUx-_5FFEOuzXBxhCyOlTtpmo7TKrW7jRNlQNegubYkTFrs08_QxLTijaFNImAnEAOwf69Z__93jP44nHOun-pjCPBxz3Qt3pdygMRRnw67v24uz7zehc-TuaMqvswIlNJ5j6mjM4pVz5WywX1AzHvZw_01-39IImVbrxVRFE8yB7CgRBSv1W3xD5-9G3XwoNHHy99APTd0scPPrD03YOPZ76tb2Y-Hjz704Jwyu6JUjKaJGmLWFB-GQQi4QoPCr9iEoaR0ljkWbOShMcLIvU4b_V4g_SJ8W_CYj3Sl_-BB4b3LfAJiWn_O2Ukfcsr5Gi4IbdHG3LobsgzG7yNztT4A1Pn5bGhde5Z5xCZC7SOxesUedEG16tCe1YJ100Z94O5ns-faRDFpUCHBVBUCrRB09iGhhYWaKF9OL9CsHfHbhMqODKcVlGoyrmVPBAZdq4ET-JvEaNxTdxciT5z6U70AWFBoucSra8FlrGi84mGoPIVQwCzuKGZ7qNq21Wge6Ty4w2JY8qnaU8Ns4G9MYGRN-hsTOB6xxA4JZPjIhuvj97n9CtB0oemqfMb53fotc3xWxQvU7dVYJorHqzmdCbEn2RR14W-LSo3890Z7iz3TMS0gWG5QUfDhoapFbMPx90sZuNhB1Xh7PyUlAQzGnaVpPFMsPBXeXSg8xAbpew2Oq6kn-I2hozX0a7Z9nony8K3ei3vEsKG4D7j2LSnxoXyuQnem8g8we80SOGBWfjAKq58cLCU1c4UHkBzAasMdn1xjyX9tgnjXLfFO1yO6RTrTcPDYTr7L0sseTC7IvKLkNE_wRVhryZmBtkkpxCYYkyTSk_l97Rcz7LcvGV7WilBM7u619CJXq3QCNocmNum0gaK9dTR4TCHdZAt4LVEtrbEX-4LxwNV469kMZUkpJ2alhZKH5Ag55QOSKDTYnl-cuoFTwLzRLzZ7s02zxFAs8-ky1VzXbTrjsPEtHOXSikJVvas035zrYfNtlrABFXDPDGqFmBE9UL-yvVrtkPnR5VeO5grFXVRsbQDq-SCn7I-qfxGOJlmw2jwed17jZElxq2whFn-jrWTJS7ZhCgpGvr1gl0wQz4hUCUzRLJ7Q6TiVHZX_R7JFoPnnyD-B9AF2SI=

@gladykov At one point, I had considered removing UMLet from Kroki because its usage was relatively low. Can you tell me why you use UMLet rather than PlantUML or other solutions that offer the same type of diagrams? Is there a killer feature, or is it more a matter of habit?

**Comment by gladykov** [comment] 2024-04-01 12:30
Thank you @ggrossetie for trying here.

We provide our users with ability to generate multiple types of diagrams, depending on what they will choose. So they are free to use Umlet or PlantUML or others. If UMLet was removed from Kroki, we would have to introduce alternative solution. Doable on our side, since libs are there, still a hassle.

I do not know history context of this project, so treat it as a blind shot, but why not just slap full version of library? If any cons, still would be better than nothing.

**Comment by ggrossetie** [comment] 2024-04-01 16:13
> I do not know history context of this project, so treat it as a blind shot, but why not just slap full version of library? If any cons, still would be better than nothing.

We don't really need the full version of the library since it includes a GUI. Also, the stripped down version is not really the issue. The root cause is that we are using GraalVM to produce a binary and dynamic calls need to be identified otherwise they are not included in the binary.

Previously, we were using UMLet as a Java library but it greatly affected performance as the library could enter infinite loops or consume a lot of resources (on large diagrams). That's why we are calling UMLet as a command.

**Comment by ggrossetie** [comment] 2024-04-01 16:29
There was a typo in the binary generation. It seems to be working with the latest release:

![out](https://github.com/yuzutech/umlet/assets/333276/5aef4870-634c-4600-8517-5795ebda99de)


It will be available in the next release of Kroki.

Fixed in https://github.com/yuzutech/umlet/commit/5e97a8e3001041350e23e57ea278e3227b0afc2a

**Closed as completed by ggrossetie** 2024-04-01 16:29 UTC

**Comment by gladykov** [comment] 2024-04-02 00:02
Thank you so much!
